package engine.common.component;

import engine.common.physics.Contact;

public interface Collidable {

    /**
     * Specifies to the game how to update this object when it enters a collision with another object.
     * @param contact the contact generated by the collision in question
     */
    void onCollisionEnter(Contact contact);
}
