package engine.common.component;

import engine.common.physics.Contact;

public interface Collidable {

    /**
     * Specifies to the game how to update this object when it enters a collision with another object.
     * @param contact the contact generated by the collision in question
     */
    void onCollisionEnter(Contact contact);

    /**
     * Specifies to the game how to update this object for every update which it remains in contact after collision enter.
     * @param contact the contact generated by the collision in question
     */
    void onCollisionStay(Contact contact);

    /**
     * Specifies to the game how to update this object when it leaves contact with another object.
     * @param other the object which this object collided with at a previous time
     */
    void onCollisionExit(GameObject other);
}
