package engine.common.physics;

import engine.common.component.GameObject;
import processing.core.PVector;

/**
 * The contact response generated by the contact of two rectangular objects.
 */
public class BoxContact extends Contact {

    public BoxContact(PVector normal, float penetration, GameObject A, GameObject B) {
        super(normal, penetration, A, B);
    }

    @Override
    public void resolve() {
        // TODO implement this
    }
}
